require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'data/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/puma.rb'
    - 'config/environments/*'

# Rails rubocop config
Rails:
    Enabled: true

Rails/Presence:
    Enabled: false

# RSpec rubocop config
RSpec:
    Enabled: true

RSpec/ContextWording:
    Prefixes:
      - when
      - with
      - without
      - and

RSpec/DescribeClass:
    Exclude:
        - 'spec/models/db_seeds_spec.rb'
        - 'spec/views/**/*'
        - 'spec/i18n_spec.rb'

RSpec/Dialect:
    PreferredMethods:
        background: :before
        scenario:   :it
        xscenario:  :xit
        given:      :let
        given!:     :let!
        feature:    :describe
    Exclude:
        - 'spec/features/**/*'

RSpec/ExampleLength:
    Max: 10
    Exclude:
        - 'spec/features/**/*'

RSpec/MultipleExpectations:
    Max: 3
    Exclude:
        - 'spec/features/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
    Max: 4

# RSpecRails rubocop config
RSpecRails:
    Enabled: true

# Standard rubocop config
Bundler/OrderedGems:
    Enabled: false

Layout/EndOfLine:
   EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'
    Exclude:
        - 'spec/**/*'

Metrics/BlockLength:
    Max: 40
    Exclude:
        - 'spec/**/*'

Metrics/ClassLength:
    Enabled: false

Layout/LineLength:
    Max: 120
    Enabled: false
    AllowedPatterns:
        - 'it .* do$'
        - 'context .* do$'
        - 'scenario .* do$'

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/ModuleLength:
    Exclude:
        - 'spec/models/**/*'
        - 'spec/controllers/**/*'

Metrics/ParameterLists:
  Max: 6

Style/Alias:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/HashEachMethods:
    Enabled: false

Style/HashSyntax:
    EnforcedShorthandSyntax: consistent

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/WordArray:
    Enabled: false
