require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'data/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/puma.rb'
    - 'config/environments/*'

Rails:
    Enabled: true

Rails/Presence:
    Enabled: false

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EndOfLine:
   EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'
    Exclude:
        - 'spec/**/*'

Layout/LineLength:
    Max: 120
    Enabled: false
    AllowedPatterns:
        - 'it .* do$'
        - 'context .* do$'
        - 'scenario .* do$'

Metrics/BlockLength:
    Max: 40
    Exclude:
        - 'spec/**/*'


# Migration/RequireUUIDPrimaryKeys:
#   Enabled: false
#   Include:
#     - 'db/migrate/*.rb'

# Migration/RequireLimitOnString:
#     Include:
#         - 'db/migrate/*.rb'

RSpec/DescribeClass:
    Exclude:
        - 'spec/models/db_seeds_spec.rb'
        - 'spec/views/**/*'
        - 'spec/i18n_spec.rb'

RSpec/Capybara/FeatureMethods:
    Exclude:
        - 'spec/features/**/*'

RSpec/MultipleExpectations:
    Max: 3
    Exclude:
        - 'spec/features/**/*'

RSpec/ExampleLength:
    Max: 10
    Exclude:
        - 'spec/features/**/*'

RSpec/NestedGroups:
    Max: 4

RSpec/ContextWording:
    Prefixes:
      - when
      - with
      - without
      - and

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/ModuleLength:
    Exclude:
        - 'spec/models/**/*'
        - 'spec/controllers/**/*'

Style/HashSyntax:
    EnforcedShorthandSyntax: consistent

Style/HashEachMethods:
    Enabled: false
